export { default as Navbar } from './navbar/Navbar'
export { default as Movies } from './movies/Movies'
export { default as Loading } from './loading/Loading'
export { default as SearchInput } from './search-input/SearchInput'
export { default as LatestMovieCard } from './movies/LatestMovieCard'
export { default as WatchedBasedRecommendations } from './WatchedBasedRecommendations'